### ISSUE TITLE
Setting SSL options

### ISSUE THREAD

**Issue by wvengen** [godfat/rest-core#15]
I'd like to communicate with a test server that has a self-signed SSL certificate for HTTPS. Where can I set the SSL options to provide the CA or set verification to none?

I can find the HTTPClient in [http-client.rb](https://github.com/godfat/rest-core/blob/master/lib/rest-core/engine/http-client.rb#L8), but I don't quite see how to access it from a middleware, for example, to access its [ssl_options](http://www.rubydoc.info/gems/httpclient/HTTPClient/SSLConfig) member.

**Comment by godfat** [comment]
Sorry that there's no way to do this at the moment. I'll add this.

**Comment by wvengen** [comment]
Thanks, looking forward to it!

**Comment by godfat** [comment]
Would let you know when it's done. Thanks for using :)

**Comment by godfat** [comment]
This is definitely not the best interface for this, but it should be flexible and similar to what we have right now. Please check if this works for you?

https://github.com/godfat/rest-core#configure-the-underlying-http-engine

Please let me know if you have any suggestion, too. Thanks!

**Comment by wvengen** [comment]
Yes, it works. It could indeed be more beautiful, but I'm glad that there is a way now. Thanks!!
