### ISSUE TITLE
Listen for "child_added"

### ISSUE THREAD

**Issue by holgersindbaek** [godfat/rest-core#17]
Is it possible for me to listen for when a child is added in my firebase with this library? If so, how would you do it?

**Comment by godfat** [comment]
Yes, please checkout [SSE](https://github.com/godfat/rest-core#sse-server-sent-events) and use [rest-firebase](https://github.com/CodementorIO/rest-firebase) for accessing firebase.

**Comment by holgersindbaek** [comment]
Thanks for the quick response. I don't see where it listens for "child_added" though?

**Comment by godfat** [comment]
Whenever it happens, it would call your `onmessage` callback.

``` ruby
es.onmessage{ |event, data, sock| p event, data } # Called for each message
```

I don't really remember what the event would be, maybe `put`. Any event for the particular node would be notified.

**Comment by holgersindbaek** [comment]
Oh, cool. I'll check it out. Thanks again.
